name: Build RareCloud Proxies v1.5.2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl jq openssl coreutils

      - name: Run argosbx_refined_v1.3.sh (config + systemd generation)
        run: |
          sudo bash argosbx_refined_v1.3.sh
          echo "✅ Configuration and service generation completed."

      - name: Copy generated files from root for upload
        run: |
          sudo mkdir -p ./agsbx_artifact
          sudo cp -r /root/.agsbx/* ./agsbx_artifact/
          sudo chown -R $USER:$USER ./agsbx_artifact
          echo "✅ Copied files to ./agsbx_artifact"

      - name: Display subscription links
        run: |
          echo "=========== RareCloud Subscriptions ==========="
          cat ./agsbx_artifact/jh.txt || echo "jh.txt not found!"
          echo "==============================================="

      - name: Upload generated artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rarecloud-proxy-configs
          path: ./agsbx_artifact/
